### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by divyaaggarwal1998** [CharmySoft/tic-tac-toe-in-python#1]
I tried it in my PC, but found an error as follows:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'

I am using python 2.7, Please somebody help.

**Comment by yumin-chen** [comment]
It seems like you are missing the module `tkinter`, you can see how to install `tkinter` on Windows [here](https://www.google.com/search?q=how+to+install+tkinter+on+windows).

I hope this helps. :)
